### ISSUE TITLE
It whispers people when I log in

### ISSUE THREAD

**Issue by Rentapest** [funkydude/BadBoy_Levels#8] opened 2019-07-05 15:18 UTC
I am running BadBoy v8.2.1 and BadBoy_Levels v8.2.0 (released 06-25-2019) and am also running ElvUI v11.16 (released 07-05-2019).

This issue has beening happening since I installed the addon last year, but it is starting to get problematic now.

If someone from my Guild has whispered me, as soon as I "/reloadui" or log into the game, the BadBoy_Levels addon whispers the person with: "BadBoy_Levels: You do not meet the requirements to whisper me"

In the BadBoy addon settings panel in-game the settings are as follows:
UNCHECKED - Show spam in button tooltip
CHECKED - Disable button pulse animation
UNCHECKED - Show the button more frequently

BadBoy_Levels v8.2.0 settings in-game are as follows:
(101, 59, 5) Required Levels - All greyed out
CHECKED - Block all whispers
CHECKED - Allow Friends
CHECKED - Allow Guild
UNCHECKED - Allow Group

BadBoy_Guilded v8.0.0
UNCHECKED - Remove guild invite whispers
UNCHECKED - Block Guild Invites

BadBoy_Ignore v8.2.0
(Only 4 players are in my block list, all cross-realm players that the default ignore list cannot block)

BadBoy_CCleaner v8.2.0
"a*al"
"r**e"
(Only the 2 defauly words are in the list)

**Comment by funkydude** [comment] 2019-07-07 00:54
Please right click the addon in your twitch client and swap it to the alpha release. Update to the latest alpha and let me know if the issue is gone.

**Comment by Rentapest** [comment] 2019-07-10 12:11
Thank you for your reply. I do not have the twitch client, but I went to the curseforge site and re-downloaded the addon and installed it.

It says it is v8.2.0 and was last updated July 8th 2019. After installing this version, I am still experiencing it whispering people in my Guild when I log in or reload the UI.

**Comment by funkydude** [comment] 2019-07-10 15:56
@Rentapest That's not the alpha, the alpha is only downloadable if you click "view all" in the files section.

**Comment by funkydude** [comment] 2019-07-21 15:20
Closing. No interest from the reporter.

**Closed as completed by funkydude** 2019-07-21 15:20 UTC
