### ISSUE TITLE
Blocking 70s "for too low of level"

### ISSUE THREAD

**Issue by Dalarrus** [funkydude/BadBoy_Levels#11] opened 2023-05-18 21:20 UTC
I suspect the issue of /who being broken has this happening because it can't get the level of the person.

Either add failure conditions properly for when /who returns no results, or at least add some basic debug text saying that badboy thinks you're level NULL etc, so you can properly try whispering them again, hoping /who and/or your addon decides to work properly.

If this is intentional, it should just say you aren't accepting whispers at all when setting the min level above the level cap. Because telling a 70 they're too low level to whisper you is not exactly clear communication.

**Comment by funkydude** [comment] 2023-05-19 17:31
This addon doesn't use the Who system whatsoever. Please add more detail to your report, like screenshots, your level, the target users level, if you are friends, guildmates, etc.

**Comment by Dalarrus** [comment] 2023-05-19 22:05
Your addon is saying, to level 70s, that their level is to low and that's why they're being spam blocked.

But at that point, that's not why they're being filtered, at that point you're filtering everyone, so you should just say you aren't accepting whispers.

I don't know if your addon was bugging out and not getting the level correctly, or if this is just how it responds to the level setting being configured higher, but either way, it sounds like an addon failing to get someone's level, but then completely keeps you from communicating to the person that their addon is causing/having issues.

**Comment by funkydude** [comment] 2023-05-20 09:25
You've not provided the information you were asked for. If you're unwilling to do this, you can go ahead and close this. Understand that you're the only person to report this, so the issue is unique to you, and it needs information from you to debug further.

**Comment by Dalarrus** [comment] 2023-05-21 09:35
I was not the person with the addon installed that had the issue.

I could not whisper them because of your addon.

I am asking for a lexical change to the reply it gives so that it is clear whether it is a bug of not reading levels correctly, or if they've just blocking everyone.

**Comment by funkydude** [comment] 2023-05-22 06:51
There is a separate option that people can use to flat out block whispers, and that sends a different whisper. But there is no requirement to use that option, and people can choose to set impossible levels also (which accomplishes the same thing).

Closing this as there is no bug here as far as I can tell, and it is by design that it doesn't specify the specific level you must be to bypass the block.

**Closed as not planned by funkydude** 2023-05-22 06:51 UTC
Labels: retail
